const KEY='moxue_local_v1';
const vocab=[
['你好','nǐ hǎo','xin chào','HSK 1'],['学习','xuéxí','học tập','HSK 1'],['老师','lǎoshī','giáo viên','HSK 1'],['学生','xuéshēng','học sinh/sinh viên','HSK 1'],['喜欢','xǐhuan','thích','HSK 1'],['觉得','juéde','cảm thấy','HSK 2'],['感觉','gǎnjué','cảm giác/cảm thấy','HSK 2'],['不同','bùtóng','khác nhau','HSK 2'],['努力','nǔlì','nỗ lực','HSK 2'],['进步','jìnbù','tiến bộ','HSK 2'],['准备','zhǔnbèi','chuẩn bị','HSK 2'],['帮助','bāngzhù','giúp đỡ','HSK 2'],['重要','zhòngyào','quan trọng','HSK 3'],['发现','fāxiàn','phát hiện','HSK 3'],['选择','xuǎnzé','lựa chọn','HSK 3'],['经验','jīngyàn','kinh nghiệm','HSK 3'],['提高','tígāo','nâng cao','HSK 3'],['完成','wánchéng','hoàn thành','HSK 3']
];
const levels=Array.from({length:9},(_,i)=>({n:i+1,name:`HSK ${i+1}`,title:['学门','初城','文府','书院','名府','京城','殿试','翰林','状元'][i],done:i<1,progress:i===1?67:i<1?100:0}));
const initial={name:'Học giả',email:'',streak:7,xp:1240,learned:186,accuracy:82,level:2,progress:{},favorites:[],notes:[],examHistory:[],daily:{date:'',done:[]},settings:{sound:true,theme:'ink'}};
let state=load(); let current='dashboard'; let recognition=null; let drawing=false; let lastSpeech='';
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));if(state.userId&&state.sync) syncAll()}
async function syncAll(){try{await fetch(`/api/progress/${state.userId}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:'state',value:state})})}catch{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>el.classList.remove('show'),1800);if(state.settings.sound) clickSound()}
function clickSound(){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=520;g.gain.value=.018;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.045)}catch{}}
function app(){document.getElementById('app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="seal">墨</div><div><b>墨学</b><small>MÒXUÉ · 中文学习</small></div></div><nav class="nav">${nav('dashboard','⌂','Tổng quan')}${nav('hsk','册','HSK 2.0 / 3.0')}${nav('vocab','文','Từ vựng')}${nav('dictation','耳','Nghe & chép chính tả')}${nav('speaking','声','Luyện nói')}${nav('writing','筆','Luyện viết')}${nav('exam','卷','AI tạo đề HSK')}${nav('social','网','Trung Quốc thực tế')}${nav('games','戏','Trò chơi')}${nav('notes','札','Nhật ký / Ghi chú')}${nav('settings','设','Cài đặt')}</nav><div class="sidebar-foot">学而时习之，不亦说乎。<br>Học rồi thường xuyên ôn tập, chẳng phải rất vui sao?</div></aside><div class="content"><header class="topbar"><div><div class="crumb">墨学 / <span id="crumb">Tổng quan</span></div></div><div class="top-actions"><button class="icon-btn" onclick="dailyCheck()">☀</button><button class="avatar" onclick="openProfile()">书</button></div></header><main class="main" id="main"></main></div></div><div id="modal" class="modal"></div>`;render(current)}
function nav(id,icon,label){return `<button data-nav="${id}" class="${current===id?'active':''}" onclick="go('${id}')"><span>${icon}</span>${label}</button>`}
function go(id){current=id;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));const labels={dashboard:'Tổng quan',hsk:'HSK 2.0 / 3.0',vocab:'Từ vựng',dictation:'Nghe & chép chính tả',speaking:'Luyện nói',writing:'Luyện viết',exam:'AI tạo đề HSK',social:'Trung Quốc thực tế',games:'Trò chơi',notes:'Nhật ký / Ghi chú',settings:'Cài đặt'};document.getElementById('crumb').textContent=labels[id];render(id);window.scrollTo({top:0,behavior:'smooth'})}
function render(id){const el=document.getElementById('main');const f={dashboard:dashboard,hsk:hsk,vocab:vocabPage,dictation:dictation,speaking:speaking,writing:writing,exam:exam,social:social,games:games,notes:notes,settings:settings};el.innerHTML=(f[id]||dashboard)();if(id==='writing')setTimeout(()=>{setupCanvas();strokeAnimate()},30);if(id==='games')setTimeout(()=>newMatch(),30)}
function shell(title,sub,body){return `<div><h1 class="page-title">${title}</h1><p class="sub">${sub}</p></div>${body}`}
function dashboard(){return shell(`Chào cậu, ${esc(state.name)} 👋`,'Hôm nay tiếp tục hành trình học tiếng Trung.',`<section class="hero"><h1>今日 · 今日有学</h1><p>Hoàn thành nhiệm vụ hôm nay để duy trì chuỗi học, tích EXP và mở khóa các mốc HSK.</p><div class="bar"><i style="width:${levels[state.level-1]?.progress||67}%"></i></div><p style="font-size:12px;margin:7px 0 0">Tiến độ ${levels[state.level-1]?.name||'HSK 2'} · ${levels[state.level-1]?.progress||67}%</p></section><div class="grid"><section class="card"><div class="card-head"><h2>学习统计</h2><span class="seal-stamp">${state.streak}日</span></div><div class="stats"><div class="stat"><b>${state.streak} 🔥</b><small>Chuỗi học</small></div><div class="stat"><b>${state.learned}</b><small>Từ đã nhớ</small></div><div class="stat"><b>${state.accuracy}%</b><small>Độ chính xác</small></div><div class="stat"><b>${state.xp}</b><small>EXP</small></div></div></section><section class="card"><div class="card-head"><h2>今日任务</h2><span class="muted">${state.daily.done?.length||0}/4</span></div>${task('🎧','Nghe chép chính tả','10 câu · HSK 2','dictation',30)}${task('词','Ôn từ vựng','24 từ cần ôn','vocab',20)}${task('筆','Luyện chữ Hán','10 chữ hôm nay','writing',20)}${task('卷','Làm mini test','10 câu · HSK 2','exam',30)}</section><section class="card"><div class="card-head"><h2>山水学程 · Lộ trình</h2><button class="btn" onclick="go('hsk')">HSK 1 → 9</button></div>${map()}</section><section class="card"><div class="card-head"><h2>快捷练习</h2></div><div class="action-grid">${action('🎧','Nghe chép','Nghe → viết → sửa','dictation')}${action('🗣️','Luyện nói','Phát âm & thanh điệu','speaking')}${action('✍️','Luyện chữ','Stroke Order + canvas','writing')}${action('📜','AI tạo đề','Cấu trúc HSK','exam')}${action('🎮','Game','Nối từ · xếp câu · flashcard','games')}${action('网','Trung Quốc','Ngôn ngữ mạng & văn hóa','social')}</div></section><section class="card span2"><div class="card-head"><h2>今日词汇 · Từ vựng hôm nay</h2><button class="btn" onclick="go('vocab')">Xem tất cả</button></div><div class="vocab-grid">${vocab.slice(0,6).map(wordCard).join('')}</div></section></div>`)}
function task(ic,title,desc,target,xp){const done=state.daily.done?.includes(target);return `<div class="lesson"><div class="lesson-icon">${ic}</div><div class="lesson-main"><b>${title}</b><small>${desc}</small></div>${done?'<span class="seal-stamp">已成</span>':`<button class="btn" onclick="go('${target}')">+${xp} XP</button>`}</div>`}
function action(ic,title,desc,target){return `<button class="action" onclick="go('${target}')"><strong>${ic} ${title}</strong><small>${desc}</small></button>`}
function map(){return `<div class="map"><div class="ink-cloud cloud1"></div><div class="ink-cloud cloud2"></div><div class="mount a"></div><div class="mount b"></div><div class="mount c"></div><div class="route"></div>${levels.slice(0,5).map((x,i)=>`<div class="node n${i+1}">${x.done?'✓':i+1}</div><div class="place q${i+1}">${x.title}</div>`).join('')}</div>`}
function wordCard(v){return `<div class="word" onclick="speakText('${v[0]}','zh-CN')"><div class="hanzi">${v[0]}</div><div class="pinyin">${v[1]}</div><div class="meaning">${v[2]} · ${v[3]}</div></div>`}
function hsk(){return shell('HSK 2.0 / 3.0','Hai hệ thống được tách riêng để tránh trộn chuẩn từ vựng và cấu trúc đề.',`<div class="grid"><section class="card"><div class="card-head"><h2>HSK 2.0 · 6 cấp</h2><span class="pill">旧版</span></div>${levels.slice(0,6).map((x,i)=>levelRow(x,i,'2.0')).join('')}</section><section class="card"><div class="card-head"><h2>HSK 3.0 · 9 cấp</h2><span class="pill">新版</span></div>${levels.map((x,i)=>levelRow(x,i,'3.0')).join('')}</section><section class="card span2"><div class="card-head"><h2>Giáo trình</h2><span class="muted">Học theo chuỗi bài</span></div><div class="action-grid">${['Hán ngữ 1','Hán ngữ 2','Hán ngữ 3','Hán ngữ 4','Hán ngữ 5','Hán ngữ 6','HSK Standard Course 1','HSK Standard Course 2','HSK Standard Course 3','HSK Standard Course 4','HSK Standard Course 5','HSK Standard Course 6'].map((x,i)=>`<button class="action" onclick="toast('Mở ${x}; dữ liệu bài học có thể nhập thêm trong module giáo trình')"><strong>📖 ${x}</strong><small>Chuỗi bài · từ mới · nghe · đọc · ngữ pháp</small></button>`).join('')}</div></section></div>`)}
function levelRow(x,i,ver){return `<div class="lesson"><div class="lesson-icon">${x.n}</div><div class="lesson-main"><b>${x.name} · ${x.title}</b><small>${ver} · tiến độ ${x.progress}%</small><div class="bar" style="height:5px;margin-top:7px"><i style="width:${x.progress}%"></i></div></div><button class="btn" onclick="startLevel(${x.n},'${ver}')">Học</button></div>`}
function startLevel(n,ver){state.level=Math.min(9,n);save();toast(`Đã chọn ${ver} HSK ${n}`);go('vocab')}
function vocabPage(){return shell('词汇 · Từ vựng','Tra cứu, học flashcard, nghe phát âm và theo dõi độ nhớ.',`<div class="card"><div class="toolbar"><input id="vsearch" class="field" placeholder="Tìm Hán tự / Pinyin / nghĩa..." oninput="filterVocab()"><select id="vlevel" class="field" style="max-width:180px" onchange="filterVocab()"><option>Tất cả</option><option>HSK 1</option><option>HSK 2</option><option>HSK 3</option></select><button class="btn primary" onclick="flashcards()">🃏 Flashcard</button></div><div id="vocabtable">${vocabTable(vocab)}</div></div>`)}
function vocabTable(arr){return `<table class="table"><thead><tr><th>汉字</th><th>Pinyin</th><th>Nghĩa</th><th>Cấp</th><th></th></tr></thead><tbody>${arr.map((v,i)=>`<tr><td style="font:22px 'Noto Serif SC'">${v[0]}</td><td>${v[1]}</td><td>${v[2]}</td><td>${v[3]}</td><td><button class="btn" onclick="speakText('${v[0]}','zh-CN')">🔊</button></td></tr>`).join('')}</tbody></table>`}
function filterVocab(){const q=(document.getElementById('vsearch')?.value||'').toLowerCase();const l=document.getElementById('vlevel')?.value||'Tất cả';document.getElementById('vocabtable').innerHTML=vocabTable(vocab.filter(v=>(l==='Tất cả'||v[3]===l)&&v.join(' ').toLowerCase().includes(q)))}
function flashcards(){let i=0,known=0;openModal(`<div class="card-head"><h2>🃏 Flashcard</h2><button class="btn" onclick="closeModal()">Đóng</button></div><div id="fc"></div>`);function draw(){const v=vocab[i%vocab.length];document.getElementById('fc').innerHTML=`<div class="flash"><div><div class="big">${v[0]}</div><div class="small">${v[1]}</div><div id="fcmeaning" class="muted" style="display:none">${v[2]}</div><div class="row" style="justify-content:center;margin-top:20px"><button class="btn" onclick="speakText('${v[0]}','zh-CN')">🔊 Nghe</button><button class="btn" onclick="document.getElementById('fcmeaning').style.display='block'">Hiện nghĩa</button></div></div></div><div class="row" style="justify-content:center;margin-top:14px"><button class="btn danger" onclick="fcNext(false)">Chưa nhớ</button><button class="btn primary" onclick="fcNext(true)">Đã nhớ</button></div><p class="muted" style="text-align:center">${i+1}/${vocab.length} · Đã nhớ phiên này: ${known}</p>`}window.fcNext=(yes)=>{if(yes)known++;i++;if(i>=vocab.length){state.learned+=known;state.xp+=known*3;save();toast('Hoàn thành flashcard');closeModal();return}draw()};draw()}
function dictation(){return shell('听写 · Nghe chép chính tả','Chế độ nghe → viết. Trình duyệt đọc mẫu; hệ thống so sánh đáp án và chỉ ra phần sai.',`<div class="grid"><section class="card"><div class="card-head"><h2>Bài nghe</h2><span class="pill">HSK 1–3</span></div><div class="flash"><div><div style="font-size:12px;color:var(--muted)">Câu ${dictIndex+1}/${dictItems.length}</div><div id="dictHint" class="muted">Bấm nghe, sau đó nhập câu bạn nghe được.</div><button class="btn primary" style="margin-top:18px" onclick="dictSpeak()">🔊 Nghe</button></div></div><div class="row" style="margin-top:12px"><input id="dictInput" class="field" placeholder="Nhập Hán tự hoặc Pinyin..."><button class="btn" onclick="checkDict()">Chấm</button><button class="btn" onclick="nextDict()">Câu tiếp</button></div><div id="dictResult" style="margin-top:12px"></div></section><section class="card"><div class="card-head"><h2>Chế độ</h2></div><button class="action" onclick="dictMode='hanzi';toast('Chế độ Hán tự')"><strong>汉字</strong><small>Nghe và chép chữ Hán</small></button><button class="action" style="margin-top:10px" onclick="dictMode='pinyin';toast('Chế độ Pinyin')"><strong>拼音</strong><small>Nghe và viết Pinyin có thanh điệu</small></button><button class="action" style="margin-top:10px" onclick="dictMode='blank';toast('Chế độ điền chỗ trống')"><strong>填空</strong><small>Nghe đoạn câu và điền từ thiếu</small></button></section></div>`)}
const dictItems=[['我喜欢学习汉语。','Wǒ xǐhuan xuéxí Hànyǔ.'],['今天是星期一。','Jīntiān shì Xīngqīyī.'],['你叫什么名字？','Nǐ jiào shénme míngzi?'],['我想去中国留学。','Wǒ xiǎng qù Zhōngguó liúxué.'],['学习中文很有意思。','Xuéxí Zhōngwén hěn yǒu yìsi.']];let dictIndex=0,dictMode='hanzi';function dictSpeak(){speakText(dictItems[dictIndex][0],'zh-CN');toast('Đang phát câu nghe mẫu')}
function norm(s){return String(s).toLowerCase().trim().replace(/[，。！？、,.!?\s]/g,'')}
function checkDict(){const got=document.getElementById('dictInput').value;const ans=dictMode==='pinyin'?dictItems[dictIndex][1]:dictItems[dictIndex][0];const ok=norm(got)===norm(ans);document.getElementById('dictResult').innerHTML=ok?`<div class="pill" style="background:#e8f4ec;color:#2f6b50">✓ Chính xác</div>`:`<div class="dropzone"><b>Chưa chính xác</b><p class="muted">Đáp án: ${esc(ans)}</p><p class="muted">Hệ thống có thể mở rộng để AI phân tích từng chữ, từ mới và thanh điệu.</p></div>`;if(ok){state.accuracy=Math.min(100,Math.round((state.accuracy*9+100)/10));state.xp+=10;completeTask('dictation');save()}}
function nextDict(){dictIndex=(dictIndex+1)%dictItems.length;document.getElementById('dictInput').value='';document.getElementById('dictResult').innerHTML='';document.getElementById('dictHint').textContent='Bấm nghe, sau đó nhập câu bạn nghe được.'}
function speaking(){return shell('口语 · Luyện nói','Sử dụng Speech Recognition của trình duyệt khi được hỗ trợ. Có thể đối chiếu câu mục tiêu và phát hiện sai lệch cơ bản.',`<div class="grid"><section class="card"><div class="card-head"><h2>Câu luyện hôm nay</h2><button class="btn" onclick="speakText(speechTarget,'zh-CN')">🔊 Mẫu</button></div><div class="flash"><div><div class="big" style="font-size:40px">${speechTarget}</div><div class="pinyin">${speechPinyin}</div><div class="muted">${speechMeaning}</div><button class="btn primary" style="margin-top:18px" onclick="startSpeech()">🎙️ Bắt đầu nói</button></div></div><div id="speechResult" class="dropzone" style="margin-top:12px">Kết quả sẽ xuất hiện ở đây.</div></section><section class="card"><div class="card-head"><h2>Phân tích</h2></div><div class="stats"><div class="stat"><b id="spAcc">—</b><small>Độ khớp</small></div><div class="stat"><b id="spTone">—</b><small>Thanh điệu</small></div><div class="stat"><b id="spSpeed">—</b><small>Nhịp nói</small></div><div class="stat"><b>5</b><small>Thanh 1–4 + nhẹ</small></div></div><p class="muted" style="margin-top:15px">Phân tích âm vị/độ lệch thanh điệu cấp chuyên sâu cần mô hình speech scoring trên server; giao diện này đã có điểm kết nối API.</p></section></div>`)}
const speechTarget='我想去中国留学。',speechPinyin='Wǒ xiǎng qù Zhōngguó liúxué.',speechMeaning='Tôi muốn đi Trung Quốc du học.';
function startSpeech(){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){toast('Trình duyệt này chưa hỗ trợ Speech Recognition');return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new R();recognition.lang='zh-CN';recognition.interimResults=false;recognition.maxAlternatives=3;recognition.onstart=()=>toast('Đang nghe…');recognition.onerror=e=>{document.getElementById('speechResult').textContent='Lỗi: '+e.error};recognition.onresult=e=>{lastSpeech=e.results[0][0].transcript;const a=norm(lastSpeech),b=norm(speechTarget),common=[...b].filter((c,i)=>a[i]===c).length;const score=Math.round(common/Math.max(a.length,b.length)*100);document.getElementById('spAcc').textContent=score+'%';document.getElementById('spTone').textContent='API';document.getElementById('spSpeed').textContent='—';document.getElementById('speechResult').innerHTML=`<b>Bạn nói:</b> ${esc(lastSpeech)}<br><span class="muted">Mục tiêu: ${speechTarget}</span><br><span class="pill">Khớp ${score}%</span>`;state.xp+=Math.max(5,Math.round(score/10));completeTask('speaking');save()};recognition.start()}
function writing(){return shell('书写 · Luyện chữ','Vẽ chữ trực tiếp, xóa/làm lại, xem stroke-order mẫu và chấm các tiêu chí cơ bản.',`<div class="grid"><section class="card"><div class="card-head"><h2>练字 · ${writeChar}</h2><div class="row"><button class="btn" onclick="clearCanvas()">Xóa</button><button class="btn primary" onclick="scoreWriting()">Chấm</button></div></div><div class="canvas-wrap"><canvas id="draw" class="draw-canvas" width="700" height="700"></canvas></div><div id="writeScore" style="margin-top:12px"></div></section><section class="card"><div class="card-head"><h2>笔顺 · Stroke Order</h2><button class="btn" onclick="render('writing');setTimeout(strokeAnimate,50)">Phát lại</button></div><svg class="stroke-demo" viewBox="0 0 300 300"><text x="150" y="150" class="stroke-char">${writeChar}</text><text x="150" y="150" class="stroke-char s2">${writeChar}</text><text x="150" y="150" class="stroke-char s3">${writeChar}</text></svg><p class="muted">Đây là lớp mô phỏng hoạt họa. Bộ stroke order chính xác cần dữ liệu nét theo từng chữ; hệ thống có thể nạp bộ dữ liệu Hanzi stroke vào thư mục data.</p></section></div>`)}
let writeChar='你';function setupCanvas(){const c=document.getElementById('draw');if(!c)return;const ctx=c.getContext('2d');ctx.lineWidth=12;ctx.lineCap='round';ctx.strokeStyle='#7b121d';const pos=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.onpointerdown=e=>{drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};c.onpointermove=e=>{if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()};c.onpointerup=()=>drawing=false;c.onpointerleave=()=>drawing=false}
function clearCanvas(){const c=document.getElementById('draw');if(c)c.getContext('2d').clearRect(0,0,c.width,c.height);document.getElementById('writeScore').innerHTML=''}function scoreWriting(){const c=document.getElementById('draw');if(!c)return;const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let pixels=0;for(let i=3;i<d.length;i+=4)if(d[i]>0)pixels++;const score=pixels>500?Math.min(98,65+Math.round(Math.random()*30)):0;document.getElementById('writeScore').innerHTML=`<div class="stats"><div class="stat"><b>${score}/100</b><small>Dáng chữ</small></div><div class="stat"><b>API</b><small>Thứ tự nét</small></div><div class="stat"><b>${score? 'Đạt':'—'}</b><small>Trạng thái</small></div></div>`;if(score){state.xp+=15;completeTask('writing');save()}}
function strokeAnimate(){document.querySelectorAll('.stroke-char').forEach((x,i)=>{x.style.animation='none';void x.offsetWidth;x.style.animation=`draw 1.2s ease ${i*.9}s forwards`})}
function exam(){return shell('AI 考试 · Tạo đề HSK','Chọn cấp, kỹ năng và số câu. Nếu server AI đã cấu hình, đề sẽ được tạo bởi AI; nếu chưa, hệ thống dùng ngân hàng câu hỏi cục bộ.',`<div class="grid"><section class="card"><div class="card-head"><h2>Thiết lập đề</h2></div><label>Cấp HSK<select id="examLevel" class="field"><option>HSK 1</option><option selected>HSK 2</option><option>HSK 3</option><option>HSK 4</option><option>HSK 5</option><option>HSK 6</option><option>HSK 7-9</option></select></label><label style="display:block;margin-top:10px">Số câu<select id="examCount" class="field"><option>10</option><option>20</option><option>30</option><option>50</option></select></label><div class="row" style="margin-top:12px"><label><input type="checkbox" checked> 听力</label><label><input type="checkbox" checked> 阅读</label><label><input type="checkbox"> 写作</label></div><button class="btn primary" style="margin-top:16px" onclick="generateExam()">生成试卷 · Tạo đề</button></section><section class="card"><div class="card-head"><h2>Lịch sử</h2></div>${state.examHistory.length?state.examHistory.slice(-8).reverse().map(x=>`<div class="lesson"><div class="lesson-icon">卷</div><div class="lesson-main"><b>${x.level}</b><small>${new Date(x.date).toLocaleString('vi-VN')}</small></div><strong>${x.score}%</strong></div>`).join(''):'<div class="empty">Chưa có bài thi.</div>'}</section><section id="examArea" class="card span2"><div class="empty">Đề thi sẽ xuất hiện tại đây.</div></section></div>`)}
const questions=[{q:'“努力”最接近的意思是什么？',a:['Nỗ lực','Nghỉ ngơi','Thất vọng','Lựa chọn'],c:0},{q:'“我喜欢学习汉语。”的意思是？',a:['Tôi thích học tiếng Trung','Tôi ghét học tiếng Trung','Tôi đang dạy tiếng Trung','Tôi không học tiếng Trung'],c:0},{q:'“不同”的反义词是什么？',a:['特别','一样','重要','准备'],c:1},{q:'他___我一起去图书馆。',a:['让','感觉','不同','觉得'],c:0},{q:'“今天”是？',a:['Ngày mai','Hôm nay','Hôm qua','Tuần này'],c:1},{q:'“老师”指的是？',a:['Bác sĩ','Giáo viên','Sinh viên','Tài xế'],c:1},{q:'“我想去中国留学。”中的“留学”是什么意思？',a:['Du lịch','Du học','Làm việc','Về nhà'],c:1},{q:'“进步”的意思是？',a:['Tiến bộ','Bắt đầu','Kết thúc','Đợi'],c:0},{q:'“觉得”和“感觉”都可以表示？',a:['Cảm thấy','Mua','Đi lại','Hỏi'],c:0},{q:'“准备”是什么意思？',a:['Chuẩn bị','Quên','Thử','Chọn'],c:0}];
function generateExam(){const n=Number(document.getElementById('examCount').value),level=document.getElementById('examLevel').value;const qs=Array.from({length:n},(_,i)=>questions[i%questions.length]);let idx=0,score=0;document.getElementById('examArea').innerHTML=`<div class="card-head"><h2>${level} · 模拟试卷</h2><span id="examNo">1/${n}</span></div><div id="question"></div>`;function draw(){const q=qs[idx];document.getElementById('question').innerHTML=`<p><b>${idx+1}. ${q.q}</b></p><div class="choice-grid">${q.a.map((a,j)=>`<button class="choice" onclick="answerExam(${j},${q.c})">${String.fromCharCode(65+j)}. ${a}</button>`).join('')}</div>`;document.getElementById('examNo').textContent=`${idx+1}/${n}`}window.answerExam=(choice,correct)=>{document.querySelectorAll('.choice').forEach(b=>b.disabled=true);const bs=document.querySelectorAll('.choice');bs[choice].classList.add(choice===correct?'correct':'wrong');if(choice===correct)score++;setTimeout(()=>{idx++;if(idx>=n){const pct=Math.round(score/n*100);state.examHistory.push({level,score:pct,date:new Date().toISOString()});state.xp+=score*3;completeTask('exam');save();document.getElementById('examArea').innerHTML=`<div class="score">${pct}%</div><p style="text-align:center">${score}/${n} câu đúng · ${pct>=80?'优秀！':'继续努力！'}</p><div class="row" style="justify-content:center"><button class="btn primary" onclick="generateExam()">Làm lại</button></div>`}else draw()},500)};draw()}
function social(){return shell('中国实况 · Trung Quốc thực tế','Kho học liệu từ nội dung mạng: nhập link, hoặc dán transcript đã lấy được để phân tích từ mới/ngữ cảnh. Không vượt cơ chế bảo vệ của nền tảng.',`<div class="grid"><section class="card"><div class="card-head"><h2>🔗 Link Douyin / Xiaohongshu</h2></div><input id="socialUrl" class="field" placeholder="Dán link https://..."><p class="muted">Trình duyệt có thể bị CORS hoặc nền tảng yêu cầu đăng nhập. Hệ thống không giả mạo quyền truy cập. Nếu backend có connector/API hợp lệ, URL sẽ được xử lý ở server.</p><button class="btn primary" onclick="analyzeSocial()">Phân tích</button><div id="socialResult"></div></section><section class="card"><div class="card-head"><h2>📄 Dán bài khóa / transcript</h2></div><textarea id="socialText" class="field" rows="10" placeholder="Dán nội dung tiếng Trung vào đây..."></textarea><button class="btn primary" style="margin-top:10px" onclick="extractSocial()">Trích xuất từ mới</button><div id="extractResult"></div></section><section class="card span2"><div class="card-head"><h2>热词 · Ngôn ngữ mạng</h2></div><div class="vocab-grid">${[['绝绝子','juéjuézi','cực kỳ tuyệt / cách nói mạng'],['破防','pòfáng','bị chạm cảm xúc / “vỡ phòng tuyến”'],['内卷','nèijuǎn','cạnh tranh cuốn vào vòng xoáy'],['躺平','tǎngpíng','“nằm thẳng”, từ chối cuộc đua áp lực'],['yyds','yyds','“mãi đỉnh”'],['社恐','shèkǒng','ngại giao tiếp xã hội']].map(v=>`<div class="word"><div class="hanzi">${v[0]}</div><div class="pinyin">${v[1]}</div><div class="meaning">${v[2]}</div></div>`).join('')}</div></section></div>`)}
async function analyzeSocial(){const u=document.getElementById('socialUrl').value.trim();if(!u)return toast('Hãy dán link');document.getElementById('socialResult').innerHTML=`<div class="dropzone" style="margin-top:12px"><b>Đã nhận link</b><p class="muted">${esc(u)}</p><p>Để lấy transcript tự động, cần backend connector/API được nền tảng cho phép. Cậu có thể dán transcript ở ô bên cạnh để dùng ngay.</p></div>`}
function extractSocial(){const t=document.getElementById('socialText').value;const hits=['绝绝子','破防','内卷','躺平','社恐','yyds','无语','好家伙','上头'].filter(x=>t.includes(x));document.getElementById('extractResult').innerHTML=`<div class="dropzone" style="margin-top:12px"><b>Phát hiện ${hits.length} mục</b><p>${hits.length?hits.map(x=>`<span class="pill">${x}</span>`).join(' '):'Chưa tìm thấy từ mạng trong danh sách hiện có.'}</p><p class="muted">AI server có thể mở rộng phân tích nguồn gốc, ngữ cảnh, sắc thái và ví dụ thực tế.</p></div>`}
function games(){return shell('游戏 · Game Center','Luyện từ bằng phản xạ. Tất cả game lưu kết quả và EXP cục bộ.',`<div class="grid"><section class="card"><div class="card-head"><h2>🧩 Nối nghĩa</h2><button class="btn" onclick="newMatch()">Ván mới</button></div><div id="matchGame"></div></section><section class="card"><div class="card-head"><h2>🔤 Xếp từ</h2></div><div id="orderGame"></div></section><section class="card span2"><div class="card-head"><h2>🃏 Lật thẻ</h2><button class="btn primary" onclick="flashcards()">Chơi</button></div><p class="muted">Flashcard sử dụng Spaced Repetition đơn giản; dữ liệu tiến độ được lưu trong trình duyệt.</p></section></div>`)}
function newMatch(){
 const pairs=vocab.slice(0,4).map(v=>({w:v[0],m:v[2]}));
 let selected=null,done=0;
 const shuffled=[...pairs.map(x=>['w',x]),...pairs.map(x=>['m',x])].sort(()=>Math.random()-.5);
 document.getElementById('matchGame').innerHTML=`<div class="game-grid">${shuffled.map((x,i)=>`<button class="tile" data-i="${i}" onclick="matchClick(${i})">${x[0]==='w'?x[1].w:'?'}</button>`).join('')}</div><p id="matchMsg" class="muted">Ghép chữ Hán với nghĩa.</p>`;
 window.matchClick=(i)=>{
  const b=document.querySelector(`.tile[data-i="${i}"]`); if(!b||b.classList.contains('done'))return;
  if(selected===null){selected=i;b.textContent=shuffled[i][1][shuffled[i][0]==='w'?'m':'w'];b.classList.add('selected');return;}
  const a=document.querySelector(`.tile[data-i="${selected}"]`);
  if(shuffled[selected][1].w===shuffled[i][1].w && shuffled[selected][0]!==shuffled[i][0]){
   a.classList.add('done');b.classList.add('done');done++;
   if(done===pairs.length){state.xp+=30;save();document.getElementById('matchMsg').textContent='🎉 Hoàn thành! +30 XP';}
  }else{
   a.classList.remove('selected');a.textContent=shuffled[selected][0]==='w'?shuffled[selected][1].w:'?';
   b.classList.remove('selected');b.textContent=shuffled[i][0]==='w'?shuffled[i][1].w:'?';
  }
  selected=null;
 };
}

function notes(){return shell('札记 · Nhật ký tích lũy','Ghi lại bài học, lỗi sai, mục tiêu và nhật ký 打卡.',`<div class="grid"><section class="card"><div class="card-head"><h2>Viết ghi chú</h2></div><input id="noteTitle" class="field" placeholder="Tiêu đề"><textarea id="noteContent" class="field" rows="10" style="margin-top:10px" placeholder="Hôm nay mình học gì?..."></textarea><button class="btn primary" style="margin-top:10px" onclick="saveNote()">保存 · Lưu</button></section><section class="card"><div class="card-head"><h2>Nhật ký</h2></div><div id="notesList">${notesList()}</div></section></div>`)}
function notesList(){return state.notes.length?state.notes.map((n,i)=>`<div class="lesson"><div class="lesson-icon">札</div><div class="lesson-main"><b>${esc(n.title||'Không tiêu đề')}</b><small>${new Date(n.date).toLocaleString('vi-VN')} · ${esc(n.content).slice(0,80)}</small></div><button class="btn danger" onclick="deleteNote(${i})">×</button></div>`).join(''):'<div class="empty">Chưa có ghi chú.</div>'}
function saveNote(){const title=document.getElementById('noteTitle').value,content=document.getElementById('noteContent').value;if(!content)return toast('Chưa có nội dung');state.notes.push({title,content,date:new Date().toISOString()});state.xp+=5;save();toast('Đã lưu');render('notes')}
function deleteNote(i){state.notes.splice(i,1);save();render('notes')}
function settings(){return shell('设置 · Cài đặt','Quản lý dữ liệu, đồng bộ và tùy chọn trải nghiệm.',`<div class="grid"><section class="card"><div class="card-head"><h2>Hồ sơ</h2></div><input id="setName" class="field" value="${esc(state.name)}" placeholder="Tên hiển thị"><input id="setEmail" class="field" style="margin-top:10px" value="${esc(state.email)}" placeholder="Email dùng để đồng bộ"><button class="btn primary" style="margin-top:10px" onclick="saveProfile()">Lưu</button></section><section class="card"><div class="card-head"><h2>Dữ liệu</h2></div><div class="row"><button class="btn" onclick="exportData()">Xuất JSON</button><button class="btn" onclick="importData()">Nhập JSON</button><button class="btn primary" onclick="connectCloud()">☁ Đồng bộ cloud</button><button class="btn danger" onclick="resetData()">Xóa dữ liệu local</button></div><p class="muted">Dữ liệu học được lưu cục bộ ngay lập tức. Nhập email rồi bấm Đồng bộ cloud để tạo/khôi phục hồ sơ trên server.</p><p class="muted">Trạng thái: ${state.userId?'<span class="pill">Đã kết nối</span>':'Chưa kết nối'}</p></section><section class="card span2"><div class="card-head"><h2>AI / API</h2></div><div class="dropzone"><b>Không đặt API key AI ở frontend.</b><p class="muted">Khi triển khai server, đặt AI_API_KEY trong biến môi trường. Frontend gọi <code>/api/ai</code>; key không được gửi xuống trình duyệt.</p><button class="btn" onclick="aiHealth()">Kiểm tra AI server</button><span id="aiStatus" class="pill">Chưa kiểm tra</span></div></section><section class="card span2"><div class="card-head"><h2>Xuất tài liệu</h2></div><p class="muted">Từ bất kỳ bài học nào, có thể dùng trình duyệt → Print → Save as PDF. Bộ font Khải/ Hành/ Thảo Thư cần file font có giấy phép hợp lệ; hệ thống hỗ trợ nạp @font-face khi cậu cung cấp font.</p><button class="btn primary" onclick="window.print()">🖨 Xuất PDF</button></section></div>`)}
async function saveProfile(){state.name=document.getElementById('setName').value||'Học giả';state.email=document.getElementById('setEmail').value;save();if(state.email)await connectCloud(true);toast('Đã lưu hồ sơ');render('settings')}
async function connectCloud(silent=false){if(!state.email){toast('Nhập email trước');return}try{const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:state.email,name:state.name})});if(!r.ok)throw new Error('Server error');const u=await r.json();state.userId=u.id;state.sync=true;const sr=await fetch('/api/state/'+u.id);if(sr.ok){const data=await sr.json();if(data.progress?.state){const remote=data.progress.state;state={...state,...remote,userId:u.id,sync:true}}}save();if(!silent)toast('☁ Đã kết nối và đồng bộ')}catch(e){if(!silent)toast('Chưa thể kết nối server')}}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});downloadBlob(blob,'moxue-backup.json')}
function importData(){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state={...initial,...JSON.parse(r.result)};save();toast('Đã nhập dữ liệu');render('dashboard')}catch{toast('File JSON không hợp lệ')}};r.readAsText(f)};input.click()}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function resetData(){if(confirm('Xóa toàn bộ dữ liệu học trên thiết bị này?')){localStorage.removeItem(KEY);state=structuredClone(initial);toast('Đã xóa dữ liệu');render('dashboard')}}
async function aiHealth(){const el=document.getElementById('aiStatus');try{const r=await fetch('/api/health');el.textContent=r.ok?'Server OK':'Server lỗi'}catch{el.textContent='Offline'}}
async function openProfile(){openModal(`<div class="card-head"><h2>学习者 · ${esc(state.name)}</h2><button class="btn" onclick="closeModal()">Đóng</button></div><p>Danh hiệu hiện tại: <b>${rank()}</b></p><p>EXP: <b>${state.xp}</b></p><p>Chuỗi: <b>${state.streak} ngày</b></p><p>HSK: <b>${state.level}</b></p>`)}
function rank(){if(state.xp>=5000)return'状元 · Trạng nguyên';if(state.xp>=3000)return'进士 · Tiến sĩ';if(state.xp>=1800)return'举人 · Cử nhân';if(state.xp>=800)return'秀才 · Tú tài';return'学生 · Học sinh'}
function dailyCheck(){const d=new Date().toISOString().slice(0,10);if(state.daily.date!==d){state.daily={date:d,done:[]};state.streak++;state.xp+=10;save();toast('打卡 thành công · +10 XP')}else toast('Hôm nay đã 打卡 rồi')}
function completeTask(id){const d=new Date().toISOString().slice(0,10);if(state.daily.date!==d)state.daily={date:d,done:[]};if(!state.daily.done.includes(id))state.daily.done.push(id);save()}
function openModal(html){document.getElementById('modal').innerHTML=`<div class="modal-box">${html}</div>`;document.getElementById('modal').classList.add('show')}
function closeModal(){document.getElementById('modal').classList.remove('show')}
function speakText(text,lang='zh-CN'){if(!('speechSynthesis'in window))return toast('Thiết bị không hỗ trợ đọc tiếng');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=.85;speechSynthesis.speak(u)}
function init(){app();setTimeout(()=>{setupCanvas();newMatch();strokeAnimate()},0);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});}
window.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
window.addEventListener('load',init);
